export const CICLO_84 = [
  { manha: "D", tarde: "B", noite: "C" }, // 1
  { manha: "A", tarde: "B", noite: "C" }, // 2
  { manha: "A", tarde: "B", noite: "D" }, // 3
  { manha: "A", tarde: "B", noite: "D" }, // 4
  { manha: "A", tarde: "C", noite: "D" }, // 5
  { manha: "B", tarde: "C", noite: "D" }, // 6
  { manha: "B", tarde: "C", noite: "D" }, // 7
  { manha: "B", tarde: "C", noite: "A" }, // 8
  { manha: "B", tarde: "D", noite: "A" }, // 9
  { manha: "C", tarde: "D", noite: "A" }, // 10
  { manha: "C", tarde: "D", noite: "A" }, // 11
  { manha: "C", tarde: "D", noite: "B" }, // 12
  { manha: "C", tarde: "A", noite: "B" }, // 13
  { manha: "C", tarde: "A", noite: "B" }, // 14
  { manha: "D", tarde: "A", noite: "B" }, // 15
  { manha: "D", tarde: "A", noite: "C" }, // 16
  { manha: "D", tarde: "B", noite: "C" }, // 17
  { manha: "D", tarde: "B", noite: "C" }, // 18
  { manha: "A", tarde: "B", noite: "C" }, // 19
  { manha: "A", tarde: "B", noite: "D" }, // 20
  { manha: "A", tarde: "B", noite: "D" }, // 21
  { manha: "A", tarde: "C", noite: "D" }, // 22
  { manha: "B", tarde: "C", noite: "D" }, // 23
  { manha: "B", tarde: "C", noite: "A" }, // 24
  { manha: "B", tarde: "C", noite: "A" }, // 25
  { manha: "B", tarde: "D", noite: "A" }, // 26
  { manha: "C", tarde: "D", noite: "A" }, // 27
  { manha: "C", tarde: "D", noite: "A" }, // 28
  { manha: "C", tarde: "D", noite: "B" }, // 29
  { manha: "C", tarde: "A", noite: "B" }, // 30
  { manha: "D", tarde: "A", noite: "B" }, // 31
  { manha: "D", tarde: "A", noite: "B" }, // 32
  { manha: "D", tarde: "A", noite: "C" }, // 33
  { manha: "D", tarde: "A", noite: "C" }, // 34
  { manha: "D", tarde: "B", noite: "C" }, // 35
  { manha: "A", tarde: "B", noite: "C" }, // 36
  { manha: "A", tarde: "B", noite: "D" }, // 37
  { manha: "A", tarde: "C", noite: "D" }, // 38
  { manha: "A", tarde: "C", noite: "D" }, // 39
  { manha: "B", tarde: "C", noite: "D" }, // 40
  { manha: "B", tarde: "C", noite: "A" }, // 41
  { manha: "B", tarde: "C", noite: "A" }, // 42
  { manha: "B", tarde: "D", noite: "A" }, // 43
  { manha: "C", tarde: "D", noite: "A" }, // 44
  { manha: "C", tarde: "D", noite: "B" }, // 45
  { manha: "C", tarde: "D", noite: "B" }, // 46
  { manha: "C", tarde: "A", noite: "B" }, // 47
  { manha: "D", tarde: "A", noite: "B" }, // 48
  { manha: "D", tarde: "A", noite: "B" }, // 49
  { manha: "D", tarde: "A", noite: "C" }, // 50
  { manha: "D", tarde: "B", noite: "C" }, // 51
  { manha: "A", tarde: "B", noite: "C" }, // 52
  { manha: "A", tarde: "B", noite: "C" }, // 53
  { manha: "A", tarde: "B", noite: "D" }, // 54
  { manha: "A", tarde: "C", noite: "D" }, // 55
  { manha: "A", tarde: "C", noite: "D" }, // 56
  { manha: "B", tarde: "C", noite: "D" }, // 57
  { manha: "B", tarde: "C", noite: "A" }, // 58
  { manha: "B", tarde: "D", noite: "A" }, // 59
  { manha: "B", tarde: "D", noite: "A" }, // 60
  { manha: "C", tarde: "D", noite: "A" }, // 61
  { manha: "C", tarde: "D", noite: "B" }, // 62
  { manha: "C", tarde: "D", noite: "B" }, // 63
  { manha: "C", tarde: "A", noite: "B" }, // 64
  { manha: "D", tarde: "A", noite: "B" }, // 65
  { manha: "D", tarde: "A", noite: "C" }, // 66
  { manha: "D", tarde: "A", noite: "C" }, // 67
  { manha: "D", tarde: "B", noite: "C" }, // 68
  { manha: "A", tarde: "B", noite: "C" }, // 69
  { manha: "A", tarde: "B", noite: "C" }, // 70
  { manha: "A", tarde: "B", noite: "D" }, // 71
  { manha: "A", tarde: "C", noite: "D" }, // 72
  { manha: "B", tarde: "C", noite: "D" }, // 73
  { manha: "B", tarde: "C", noite: "D" }, // 74
  { manha: "B", tarde: "C", noite: "A" }, // 75
  { manha: "B", tarde: "D", noite: "A" }, // 76
  { manha: "B", tarde: "D", noite: "A" }, // 77
  { manha: "B", tarde: "D", noite: "A" }, // 78
  { manha: "C", tarde: "D", noite: "B" }, // 79
  { manha: "C", tarde: "A", noite: "B" }, // 80
  { manha: "C", tarde: "A", noite: "B" }, // 81
  { manha: "D", tarde: "A", noite: "B" }, // 82
  { manha: "D", tarde: "A", noite: "C" }, // 83
  { manha: "D", tarde: "A", noite: "C" }, // 84
]
