export const CICLO_42 = [
  { manha: "A", tarde: "B", noite: "C" },
  { manha: "A", tarde: "B", noite: "C" },
  { manha: "A", tarde: "B", noite: "C" },
  { manha: "A", tarde: "B", noite: "C" },
  { manha: "A", tarde: "B", noite: "C" },
  { manha: "A", tarde: null, noite: null },
  { manha: null, tarde: null, noite: null },

  { manha: "B", tarde: "C", noite: "A" },
  { manha: "B", tarde: "C", noite: "A" },
  { manha: "B", tarde: "C", noite: "A" },
  { manha: "B", tarde: "C", noite: "A" },
  { manha: "B", tarde: "C", noite: "A" },
  { manha: "B", tarde: "C", noite: null },
  { manha: null, tarde: null, noite: null },

  { manha: "C", tarde: "A", noite: "B" },
  { manha: "C", tarde: "A", noite: "B" },
  { manha: "C", tarde: "A", noite: "B" },
  { manha: "C", tarde: "A", noite: "B" },
  { manha: "C", tarde: "A", noite: "B" },
  { manha: "C", tarde: null, noite: null },
  { manha: null, tarde: null, noite: null },

  { manha: "A", tarde: "B", noite: "C" },
  { manha: "A", tarde: "B", noite: "C" },
  { manha: "A", tarde: "B", noite: "C" },
  { manha: "A", tarde: "B", noite: "C" },
  { manha: "A", tarde: "B", noite: "C" },
  { manha: "A", tarde: "B", noite: null },
  { manha: null, tarde: null, noite: null },

  { manha: "B", tarde: "C", noite: "A" },
  { manha: "B", tarde: "C", noite: "A" },
  { manha: "B", tarde: "C", noite: "A" },
  { manha: "B", tarde: "C", noite: "A" },
  { manha: "B", tarde: "C", noite: "A" },
  { manha: "B", tarde: null, noite: null },
  { manha: null, tarde: null, noite: null },

  { manha: "C", tarde: "A", noite: "B" },
  { manha: "C", tarde: "A", noite: "B" },
  { manha: "C", tarde: "A", noite: "B" },
  { manha: "C", tarde: "A", noite: "B" },
  { manha: "C", tarde: "A", noite: "B" },
  { manha: "C", tarde: "A", noite: null },
  { manha: null, tarde: null, noite: null },
]
